apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
    color: blue           # на старте направляем трафик на blue
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
