apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-go-green
  labels:
    app: myapp
    version: "2.0"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
      color: green
  template:
    metadata:
      labels:
        app: myapp
        color: green
        version: "2.0"
    spec:
      containers:
      - name: myapp-container
        image: kethisxd/do.kt3:2.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
